SELECT RI.REST_ID, RI.REST_NAME, RI.FOOD_TYPE, RI.FAVORITES, RI.ADDRESS, ROUND(AVG(RR.REVIEW_SCORE), 2) AS SCORE
FROM REST_INFO RI, REST_REVIEW RR
WHERE RI.REST_ID = RR.REST_ID
  AND RI.ADDRESS LIKE '서울%'
GROUP BY RI.REST_ID
ORDER bY AVG(RR.REVIEW_SCORE) DESC, RI.FAVORITES DESC